### ISSUE TITLE
Failed setup: Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by gitleet** [thechangelog/changelog.com#185]
I ran ./script/setup

When try and start the server I see this.

Any tips on how to resolve this?

```
changelog.com$ mix phoenix.server
mix phoenix.server is deprecated. Use phx.server instead.
[info] Running ChangelogWeb.Endpoint with Cowboy using http://0.0.0.0:4000
yarn run v1.3.2
warning package.json: No license field
$ webpack --watch-stdin --color
module.js:538
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/me/dev/sources/phoenix/changelog.com/assets/webpack.config.js:1:77)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
^C
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
```

**Comment by jerodsanto** [comment]
hmm line 17 of the setup script may not work now that all of the assets stuff has been moved from the top level of the repo to `/assets`. 

Try changing it to `cd assets && yarn install` and see if that fixes it.

(Also you should be using `mix phx.server` now since that is the newer mix tool provided by Phoenix)

**Comment by gitleet** [comment]
That worked, cool thanks!
